BaseBadge Component
directus/website pull request #16
Opened 2023-07-10 18:25 UTC by bryantgillespie

2023-07-11 08:59 UTC, rijkvanzanten requested changes

2023-07-11 08:59 UTC, rijkvanzanten commented on components/src/base-badge/base-badge.vue
> +});
Lets do this in CSS instead 👍🏻 

The color is already a class on the component so it should be doable to have a 

```css
.badge-primary {
  border-color: var(--purple-300);
}
```

2023-07-12 07:48 UTC, rijkvanzanten requested changes

2023-07-12 07:48 UTC, rijkvanzanten commented on components/src/base-badge/base-badge.vue
> +		return 'a';
But this _should_ be a router-link? In that case, lets fix the problem in Histoire rather than in the website codebase itself 👍🏻

2023-07-12 12:44 UTC, rijkvanzanten commented on components/src/base-badge/base-badge.vue
> +		return 'a';
Looks like the problem wasn't histoire in the first place! You were trying to set an `href` on a `router-link`, but `router-link` uses `to` instead of `href` for local pages 👍🏻  For this badge, be aware that you need to use `<a>` for links to pages outside of the website, and `<router-link>` for pages within

2023-07-12 13:28 UTC, bryantgillespie commented on components/src/base-badge/base-badge.vue
> +		return 'a';
Ahh - it was me 😆 
Too used to using [NuxtLink](https://nuxt.com/docs/api/components/nuxt-link) instead of router-link.

2023-07-12 13:38 UTC, bryantgillespie commented on components/src/base-badge/base-badge.vue
> +		return 'a';
Here's the source for it
https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/components/nuxt-link.ts
It has some niceties built-in like prefetching and handling external links.

Is there an easy way to just use it inside of a Nuxt project vs a Vue project (docs)?

2023-07-12 14:01 UTC, rijkvanzanten commented on components/src/base-badge/base-badge.vue
> +		return 'a';
> Is there an easy way to just use it inside of a Nuxt project vs a Vue project (docs)?

No idea, though I have my doubts it'll just work outside of the Nuxt context (as it's so dependent on the router and some other magic). It does raise the question though: should we rework the docs to Nuxt as well?

2023-07-12 14:06 UTC, paescuj commented on components/src/base-badge/base-badge.vue
> +		return 'a';
You mean adding Nuxt to context of Histoire?

2023-07-12 14:10 UTC, bryantgillespie commented on components/src/base-badge/base-badge.vue
> +		return 'a';
>  It does raise the question though: should we rework the docs to Nuxt as well?

I think so. Eventually...

I like VitePress and it's super easy to get started with but there are lots of little specific quirks that I've struggled to sort out.
But Nuxt has it's own quirks too. 

To me it makes sense that it's all unified though.

2023-07-18 20:16 UTC, paescuj commented
Closing in favor of #22.

2023-07-18 20:16 UTC, closed without merging

2023-07-18 20:33 UTC, paescuj commented on components/src/base-badge/base-badge.vue
> +		return 'a';
> No not really. I was just meaning if there was an easy way to say in this components package ..
> >  hey if this is a nuxt project use nuxt-link if not use router-link

For later: Something like this sounds like a good idea in order to be able to unify the components. For Nuxt we could maybe inject `nuxt-link` in the [module setup file](https://github.com/directus/website/blob/a0d10e963b208031e04a6179be17e4c7de9e4dcf/components/nuxt.ts).