Basic Structure
directus/website pull request #2
Opened 2023-06-06 15:59 UTC by bryantgillespie

2023-06-09 13:40 UTC, rijkvanzanten requested changes

2023-06-09 13:40 UTC, rijkvanzanten commented on .env.example
> +DIRECTUS_URL="https://your-instance.directus.appp"
```suggestion
DIRECTUS_URL="https://your-instance.directus.app"
```

2023-06-09 13:40 UTC, rijkvanzanten commented on .env.example
> +DIRECTUS_ADMIN_TOKEN="XHdfaklsdj;fladsjkfal;zj;lkda"
Do we need an _admin_ token? Do we need a token at all?

2023-06-09 13:40 UTC, rijkvanzanten commented on components/blocks/BlockComponentName.vue
> +};
Use interfaces for object structure typing

```suggestion
interface Block {
	id: string;
}
```

2023-06-09 13:40 UTC, rijkvanzanten commented on components/blocks/BlockComponentName.vue
> +});
Lets use TS to define props

```suggestion
interface BlockComponentNameProps {
  data: Block;
}

defineProps<BlockComponentNameProps>();
```

2023-06-09 13:40 UTC, rijkvanzanten commented on layouts/default.vue
> +</template>
Are those root elements still required in Nuxt?

```suggestion
<template>
	<TheHeader />
	<slot />
	<TheFooter />
</template>
```

2023-06-09 14:15 UTC, bryantgillespie commented on .env.example
> +DIRECTUS_ADMIN_TOKEN="XHdfaklsdj;fladsjkfal;zj;lkda"
Doesn't have to be an _admin_ token I guess.

2023-06-09 14:26 UTC, bryantgillespie commented on types.ts
> +// Page builder types
So would all these just be interfaces?

2023-06-19 18:28 UTC, rijkvanzanten approved these changes

2023-07-20 21:11 UTC, merged