Page Builder Base Layer
directus/website pull request #21
Opened 2023-07-17 18:47 UTC by bryantgillespie

2023-07-18 18:13 UTC, paescuj commented
Does this superseed #2?

2023-07-18 21:46 UTC, rijkvanzanten commented on site/app.vue
> +	flex-direction: column;
This feels like styling problems waiting to happen 😬

2023-07-18 21:46 UTC, rijkvanzanten commented on site/assets/css/reset.css
> +}
These aren't really resets anymore, but rather global styles

2023-07-18 21:46 UTC, rijkvanzanten commented on site/page-block-fields.ts
> +export const block_hero_headline = [
Not a fan of the mixing of camelCase and underscore 🤔

2023-07-18 21:46 UTC, rijkvanzanten commented on site/page-block-fields.ts
> +export function flattenFieldTree(fields: any[]) {
Ironically, the new SDK uses the nested structure you used above, so this is no longer needed

2023-07-18 21:52 UTC, rijkvanzanten requested changes

2023-07-18 21:52 UTC, rijkvanzanten commented on site/assets/css/reset.css
> +/* Box sizing rules */
Instead of copy pasting from https://andy-bell.co.uk/a-modern-css-reset/, lets figure out what parts of this we actually want/need, and omit the rest. There's some opinions in here that might might not have the desired effect

2023-07-19 11:38 UTC, bryantgillespie commented on site/page-block-fields.ts
> +export function flattenFieldTree(fields: any[]) {
🤣 I knew we'd be using the new SDK so that's why I wrote the fields queries with the nested structure and threw this little helper in there to make it work for the time being.

2023-07-19 22:33 UTC, merged