Page Builder > Floating Page
directus/website pull request #42
Opened 2023-07-28 19:24 UTC by bryantgillespie

**Design Example**

<img width="423" alt="ScreenShot 2023-07-28 at 15 24 12@2x" src="https://github.com/directus/website/assets/23302570/41a7c245-ce6a-4b5b-8242-5d45f521d0a9">

2023-07-28 20:12 UTC, rijkvanzanten requested changes

2023-07-28 20:12 UTC, rijkvanzanten commented on components/Block/FloatingPage.vue
> +	margin-inline: auto;
Padding and margin should be handled by the context the block is rendered in, not the block itself

2023-07-28 20:12 UTC, rijkvanzanten commented on components/Block/FloatingPage.vue
> +	@media (width > 50rem) {
Lets use container queries for this to handle the 50/50 block usage

2023-07-29 01:22 UTC, bryantgillespie commented on components/Block/FloatingPage.vue
> +	margin-inline: auto;
Gotcha - yeah I'll remove the margin here but the padding is for the content inside the 'page'.
Or should I just wrap this in another div?

![ScreenShot 2023-07-28 at 21 20 32@2x](https://github.com/directus/website/assets/23302570/c418f0e5-e44a-441d-90dd-9b5e3e23d06f)

2023-07-29 01:24 UTC, bryantgillespie commented on components/Block/FloatingPage.vue
> +	@media (width > 50rem) {
Right now the data model is setup to only allow this on a full width page block and not within the 50/50.

2023-07-31 20:21 UTC, rijkvanzanten commented on components/Block/FloatingPage.vue
> +	margin-inline: auto;
This particular padding is for the element itself, so this is the right spot 🙂 sorry 'bout the confusion

2023-07-31 20:21 UTC, rijkvanzanten commented on components/Block/FloatingPage.vue
> +	@media (width > 50rem) {
_right now_ being the key words there 😄 Lets keep things consistent and make sure any block can be rendered in any context

2023-08-24 12:08 UTC, closed without merging