Start of Dynamic OG
directus/website pull request #5
Opened 2023-06-09 13:35 UTC by bryantgillespie

2023-06-09 14:47 UTC, rijkvanzanten requested changes

2023-06-09 14:47 UTC, rijkvanzanten commented on pages/_image/pages/[slug].vue
> +const { $directus } = useNuxtApp();
Lets make sure we use comments to explain _why_, not _what_. The code that's commented on here is already self-documenting

2023-06-09 14:47 UTC, rijkvanzanten commented on server/api/og-image.post.ts
> +		// Wait for the page to load
Same note regarding comments.

2023-06-09 14:58 UTC, bryantgillespie commented on pages/_image/pages/[slug].vue
> +const { $directus } = useNuxtApp();
Yeah sorry - this was just copy / pasted from separate project aimed at beginners.

2023-06-09 15:15 UTC, bryantgillespie commented on components/image/Og.vue
> +<script setup lang="ts">
Nuxt 3 does this weird thing which is kinda nice and kinda confusing at the same time.

It will prefix all the component names with the directories they're contained in.
So an `Og` component in `/image/` directory will be called using <OgImage> inside the template.

https://nuxt.com/docs/guide/directory-structure/components#component-names

In the AgencyOS project I just left it since it was the default behavior for Nuxt. But if you'd rather, here we can disable the auto-prefix and just add it to the filename. Pretty simple change in the NuxtConfig.

2023-06-09 15:17 UTC, bryantgillespie commented on components/image/Og.vue
> +	imageUrl?: string;
Yes - these should be optional props. Again a copy / paste from the AgencyOS project.

2023-06-16 17:40 UTC, rijkvanzanten approved these changes

2023-06-16 17:40 UTC, merged