Dynamic OG Images Module
directus/website pull request #51
Opened 2023-08-24 05:44 UTC by bryantgillespie

2023-09-01 19:41 UTC, rijkvanzanten requested changes
I think og-images/dist should be in gitignore right?

2023-09-01 19:41 UTC, rijkvanzanten commented on .env.example
> +DIRECTUS_TOKEN="XHdfaklsdj;fladsjkfal;zj;lkda"
This is no longer relevant

2023-09-01 19:41 UTC, rijkvanzanten commented on modules/og-images/dist/og.js
> +import { defineComponent as r, openBlock as t, createElementBlock as s, createElementVNode as e, toDisplayString as o, createCommentVNode as l, createStaticVNode as g } from "vue";
Lets not put bundled dist code in git

2023-09-20 21:37 UTC, closed without merging

2023-09-20 21:38 UTC, bryantgillespie commented
Closed in favor of #75