base routes
directus/website pull request #6
Opened 2023-06-09 13:49 UTC by bryantgillespie

2023-06-09 14:42 UTC, rijkvanzanten requested changes

2023-06-09 14:42 UTC, rijkvanzanten commented on pages/[...slug].vue
> +page.value = data.value;
Lets just make page a computedRef?

```js
const page = computed(() => data.value);
```

2023-06-09 14:42 UTC, rijkvanzanten commented on pages/[...slug].vue
> +// https://v3.nuxtjs.org/docs/usage/data-fetching#useasyncdata
Docs link is 404

2023-06-09 17:22 UTC, bryantgillespie commented on pages/[...slug].vue
> +page.value = data.value;
Actually on testing it appears that the Nuxt team fixed the bug where you needed to call `useHead` before the first top level await on the page so we can solve this much easier now.

2023-06-16 17:41 UTC, rijkvanzanten approved these changes

2023-06-16 17:41 UTC, merged