Route Form Submissions to HubSpot Meeting Links
directus/website pull request #77
Opened 2023-10-02 14:58 UTC by bryantgillespie

2023-10-02 17:02 UTC, rijkvanzanten requested changes

2023-10-02 17:02 UTC, rijkvanzanten commented on components/Base/HsForm.vue
> +	}, 500);
This feels very brittle. Any way we can make this event-driven instead of based on a timeout?

2023-10-02 22:45 UTC, bryantgillespie commented
Thinking this should be good now.

I didn't realized HubSpot had an onFormSubmitted event (or I did and forgot about it the last time I wrote this for the old website)

Deploy Preview originally failed but I think that was because of the pressure limiter.

https://deploy-preview-77--directus-website.netlify.app/

2023-10-04 19:45 UTC, rijkvanzanten approved these changes

2023-10-04 19:45 UTC, merged